### ISSUE TITLE
arti_slot_loot.script:132: attempt to call field 'get_real_community' (a nil value)

### ISSUE THREAD

**Issue by svndvst** [ahuyn/anomaly-armor-attachments#1]
anomaly-armor-attachments.2021.12.24
Having a stable crash when trying to speak with traders (got with barman, petrenko).

arti_slot_loot.script:132: attempt to call field 'get_real_community' (a nil value)

if to unchek mod and then speak, I can load with mod againagain. with 1.2 from moddb everything is ok

**Comment by ahuyn** [comment]
Make sure you use the trader autoinject that comes bundled with this mod
